### ISSUE TITLE
That pull request a few mins ago...

### ISSUE THREAD

**Issue by tallship** [spc476/GLV-1.12556#3]
Looks good now. The table in the initial PR didn't format correctly (I was trying to keep it centered).

![2019-10-31_1656](https://user-images.githubusercontent.com/561994/67993924-19872e80-fc00-11e9-999b-e2259edfa78f.png)

I also staged it back in my fork of the patch2, so I'm not sure if it's actually part of the PR I made for you, pls advise, and I can fix that  later if you like the PR and new formatting of the README.md

Finally, I'm happy to start working on docs/manual too, running stuff by and collaborating w/you on what will/should be included in those docs.

**Comment by spc476** [comment]
As I mentioned in the pull request, I'm not a fan of Markdown and would prefer not to use it (or any other type of plain text markup)---I'm just kind of old school like that.  As for what should be included in the docs, are what I have enough to get it working on another system?  I honestly don't know because I know what I know.
